#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080

set -e

source ${OPENSHIFT_REPO_DIR}/.openshift/action_hooks/common
source ${OPENSHIFT_REPO_DIR}/.openshift/action_hooks/build
source ${OPENSHIFT_REPO_DIR}/.openshift/action_hooks/deploy

echo "Starting nginx."
${OPENSHIFT_RUNTIME_DIR}/nginx/sbin/nginx

echo "Starting php-fpm."
${OPENSHIFT_RUNTIME_DIR}/php5/sbin/php-fpm

cd ${OPENSHIFT_DATA_DIR}
source newrelic/bin/activate
newrelic_plugin_agent -c newrelic_plugin_agent.cfg
