@extends('layouts.master')

@section('title')
Nothing Interesting
@stop

@section('content')

<main class="page_content">
	<h2>Interests</h2>
	<p>I have been fascinated with electronics from a very young age. Always wanting to take things apart to see how they worked. Growing up in a fairly bad part of Mississippi, school was not my friend. So I never applied myself. Always looking forward to the day I could graduated and get away. College or University was never in my future. Half-way through high school, I enrolled in a Auto Mechanics course and did pretty well. At one point, our teacher was out sick for like a month and no sub could be found. So they split our class up and placed us in several different other classes offered by the vocational school. I just so happened to be placed in what was called, "Diversified Technologies" for a week. In this class, students were exposed to light computer programming on old Macs (AppleII's actually), but did cool things like write programs that controlled robotic arms and all sorts of cool stuff like that. Basically the equivalent to our modern day <a href="http://en.wikipedia.org/wiki/STEM_fields">STEM</a> classes some lucky middle and high school students can take that introduce them to certain paths of study within the realm of Computer Science. This was were I realized what a hugh mistake I had made in regards to my future. It was quite depressing. I ended up as a pretty good, but unhappy mechanic for roughly 10 yrs.</p>

	<h2>Day Job</h2>
	<p>My day job, for the last 18 yrs or so, is working as a copier technician. I first worked as a Xerox technician for 6 or 7 yrs. 2 years in the Mississippi, which is where my family and I are from. Later, Xerox moved my young family up to Northeast Mississippi where I worked for them another 5 - 6 years. The last 9 years have been spent at a Savin dealership here in Corinth, MS. It's an awesome job and I love the work. This career has allowed me to pursue the things that I truly love and have been interested in since I was very young.</p>
	<p>After about 4 yrs at Xerox, digital copiers were really starting to take off. So we all had to go to a class that covered computers and an intro course to networking. Why? Well, todays copiers are just tall computers that hold paper and have an attached scanner. This is the only formal training I have had as far as computers are concerned. Everything else was either self taught or looked up on the Internet. Currently, I do just about everything </p>

	<h2>How Did I Get Into Web Development</h2>
	<p>My wife and I got our first computer back in 1999. It sat around on the desk for a few months, collecting dust, until we got our first internet service account through a local ISP. While I was at work, my wife got our Windows 98 system online and when I got home, she should me what she had found on the web. When I saw my first web page (our ISP's home page) I was blown away. I had to figure out how they did that. Several months later, I found <a href="http://www.htmlgoodies.com">HTML Goodies</a>. It was a great little site put together by a fella named <a href="http://www.htmlgoodies.com/primers/perl/article.php/3478551">Joe Burns</a>. I learned on the original site. After a few months, I was able to coble together pages using HTML and CSS. I even put together a few sites on good old GeoCities. But once JavaScript really started picking up steam, I just didn't get it. People were just starting to use this language called Perl to create "dynamic" websites (whatever that was) and it was all a lot over my head. Things were starting to change really fast and it was hard to keep up. That was about the time I got hired into Xerox and for the next decade, basically, I never touch another character of code.</p>
	<p>But along came an idea back in 2009. The techs I worked with had a problem. We all did. So I set out to fix it. How hard could it be, right? I thought the best way to go about solving the problem at hand was writing a native app. So, I started teaching myself Java. Seriously, just got up on a Saturday and started performing Google searches. A month or two later, I had a few prototypes and had taught myself a lot! Not just enough Java to do the simple task I needed, but also MySQL and setting up a local database. Working with different servers, such as TomCat. Concepts of OOP (Objects Oriented Programming). Lots of really cool things! But finally, I gave up on the project due to some limitations that I did not control nor over come. Two days after publicly killing the project, a fello tech from up north sent me a message with a link, asking if what I found on the other end of that link was what I was trying to make. Hell yes it was and it was in a web page. "Brillant!", I exclaimed. I found that he was using PHP, so quickly I started digging back in to the web.</p>

	<h5>And that, as they say, is history. Boring? Yeah, but it's mine.</h5>
</main>

@stop
